apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: export
    keel.sh/policy: force
    keel.sh/trigger: poll
  name: export
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      run: export
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: export
    spec:
      containers:
      - env:
        - name: ADS_DEBUG
          value: "False"
        - name: TEST
          value: ads
        - name: SERVICE
          value: export
        - name: ENVIRONMENT
          value: dev
        - name: EXPORT_SERVICE_FROM_BBB_URL
          value: https://dev.adsabs.harvard.edu/abs
        - name: EXPORT_SERVICE_CLASSIC_EXPORT_URL
          value: http://adsabs.harvard.edu/cgi-bin/nph-abs_connect
        - name: EXPORT_SOLRQUERY_URL
          value: http://adsws/v1/search/bigquery
        - name: EXPORT_SERVICE_ADSWS_API_TOKEN
          value: 9xb8lOAMDfQtkbwIysOMkOcJqOPbtq0GSpiguSmbLx8ZTnQfUkEzn95fezOf
        - name: GUNICORN_WORKERS
          value: "2"
        - name: GUNICORN_WORKER_CLASS
          value: gevent
        - name: GUNICORN_TIMEOUT
          value: "30"
        - name: GUNICORN_WORKER_CONNECTIONS
          value: "1000"
        - name: GUNICORN_MAX_REQUESTS
          value: "1000"
        - name: GUNICORN_MAX_REQUESTS_JITTER
          value: "100"
        image: adsabs/export_service:latest
        volumeMounts:
        - name: gunicorn-config
          mountPath: /gconfig/
        imagePullPolicy: Always
        name: export
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
            httpHeaders:
            - name: X-Amzn-Trace-Id
              value: readinessProbe
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /alive
            port: 80
            httpHeaders:
            - name: X-Amzn-Trace-Id
              value: livenessProbe
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 5
        ports:
        - containerPort: 80
          protocol: TCP
        resources: 
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /gconfig/
          name: gunicorn-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: gunicorn-config
        configMap:
          name: gunicorn-config
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: export
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: export
  sessionAffinity: None
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: export
  namespace: dev
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: export
  targetCPUUtilizationPercentage: 75
